server:
  port: ${PORT:5000}
security:
  user:
    password: ${EUREKA_USER_PASSWORD:password}

eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost

---
spring:
  profiles: peer
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_PEER_URL}/eureka/
